### ISSUE TITLE
关于你们所做任务的疑问

### ISSUE THREAD

**Issue by azsxza** [PKU-ICST-MIPL/FGCrossNet_ACMMM2019#3]
看了你们的代码，所以你们的任务是在一个200类的数据集上进行训练，然后测试集也是这200类中的数据，去预测具体输入的类别，然后根据这个类别去检索？
但你们论文里说的是使用他们四个模态之间的公共表征来进行检索，确实是fc层的输出，但这个输出就是网络预测输入所属的类别了吧。
根据我对你们代码的理解，你们是对网络输入同一个类别的四种不同的数据，然后用同一个网络去判断这四种不同数据的特征属于具体哪一个类别，存下来类别后使用这些类别进行检索（test.py中的extra函数里的代码已经表示出存下来的输出是只有一个数字，所以这个应该就是类别吧）。

并且感觉你们加入ranking loss有点牵强，有点强行往检索任务上扯的意味。
所以学习到的公共表征具体是指的什么呢？

**Comment by mumuhe** [comment]
> 看了你们的代码，所以你们的任务是在一个200类的数据集上进行训练，然后测试集也是这200类中的数据，去预测具体输入的类别，然后根据这个类别去检索？
> 但你们论文里说的是使用他们四个模态之间的公共表征来进行检索，确实是fc层的输出，但这个输出就是网络预测输入所属的类别了吧。
> 根据我对你们代码的理解，你们是对网络输入同一个类别的四种不同的数据，然后用同一个网络去判断这四种不同数据的特征属于具体哪一个类别，存下来类别后使用这些类别进行检索（test.py中的extra函数里的代码已经表示出存下来的输出是只有一个数字，所以这个应该就是类别吧）。
> 
> 并且感觉你们加入ranking loss有点牵强，有点强行往检索任务上扯的意味。
> 所以学习到的公共表征具体是指的什么呢？

你好！这个任务确实是检索任务，我们是用的是最后一层的200维特征，利用距离度量实现的检索。这与分类还是有不同的，需要通过多种约束来实现四种媒体特征的统一表征，使得其能够得到一个比较不错的检索结果。如果直接按照分类来做，这样的效果是不够的。我们主要是想建立一个评测基准，供大家在细粒度跨媒体检索这个领域来做一些事情。
