### ISSUE TITLE
Questions about the code implementation

### ISSUE THREAD

**Issue by amyzx** [PKU-ICST-MIPL/FGCrossNet_ACMMM2019#5]
Hi, sorry to bother you. I have the following 4 questions.

1. I found in your dataset.py, Line 52 seems to be wrong because it needs to be in a for loop.
Please check this [line](https://github.com/PKU-ICST-MIPL/FGCrossNet_ACMMM2019/blob/b92a2aefdc7ae52069cc4353be999ac07c42af20/dataset.py#L52)
If this is correct, it means that **CudaTextDataset** only processes the last text. 

2. I am curious about the parameter **max_length** in CudaTextDataset. Why it is 448? 
   Can I change it to other number such as 64 or 128?

3. Can I process text by calling [processtxt](https://github.com/PKU-ICST-MIPL/FGCrossNet_ACMMM2019/blob/master/model.py#L149) before calling forward function? I hope processed text could have the same dimension as images, such as [3, 448, 448].

4. Can I change the **crop_size** from 448 to 48, and **scale_size** from 512 to 64?  I hope to reduce the input data. Will this change influence the model training accuracy?

Looking forward to your reply, thanks!

**Comment by thebestYezhang** [comment]
Hello, I am also curious about their work. About your questions 2，they had described in the paper, because they want to cover all items. So you can change it to smaller numbers. About the question 3, I think they did like you said. As for the last question, certainly it will decrease the score. So, are you doing this work up to now？Or you've done it?

**Comment by amyzx** [comment]
@thebestYezhang  Hi, thanks for your reply. I tried to implement the method in question 3, but not finished until now. I am not working on this project right now.

**Comment by Rose-bud** [comment]
> @thebestYezhang Hi, thanks for your reply. I tried to implement the method in question 3, but not finished until now. I am not working on this project right now.

Hi guys, I've recently wanted to do some work on fine-grained cross-modal retrieval based on this paper, but I've also encountered problems related to e.g. dataset acquisition, code reproduction after getting deeper into the paper, in your opinion, should I continue to go along with this paper? So far the dataset acquisition is much more complex than the other tasks.

**Comment by Rose-bud** [comment]
> 
Hi guys, I've recently wanted to do some work on fine-grained cross-modal retrieval based on this paper, but I've also encountered problems related to e.g. dataset acquisition, code reproduction after getting deeper into the paper, in your opinion, should I continue to go along with this paper? So far the dataset acquisition is much more complex than the other tasks.
